# Generated by Django 5.1.6 on 2025-02-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='funcionario',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
