# Generated by Django 5.1.6 on 2025-02-13 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customuser_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='funcionario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visits',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
