# Generated by Django 5.1.6 on 2025-02-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_funcionario_alter_visits_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='img',
            field=models.ImageField(default=1, upload_to='visitors'),
            preserve_default=False,
        ),
    ]
