# Generated by Django 5.1.6 on 2025-02-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_visitor_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='img',
        ),
    ]
