# Generated by Django 5.1.6 on 2025-02-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_visitor_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visits',
            options={'permissions': [('dg_view_visits', 'employee can view visits')]},
        ),
    ]
