# Generated by Django 5.1.6 on 2025-02-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_visits_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='status',
            field=models.CharField(default='Agendada', max_length=20),
        ),
    ]
