# Generated by Django 5.1.6 on 2025-02-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_customuser_photo_visitor_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('admin_permission', 'admin can view add and change branches,departments and users'), ('attendant_permission', 'attendant can view add and change visitors and visits'), ('employee_permission', 'employee can view add and change visits')]},
        ),
    ]
