# Generated by Django 5.1.6 on 2025-02-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visits',
            options={},
        ),
    ]
