# Generated by Django 5.1.6 on 2025-02-17 11:08

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_visits_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='rg',
            field=models.CharField(max_length=9, unique=True, validators=[core.validators.validate_rg]),
        ),
    ]
