# Generated by Django 5.1.6 on 2025-02-17 16:36

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_visitor_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[core.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(max_length=20, validators=[core.validators.validate_phone]),
        ),
    ]
