# Generated by Django 5.1.6 on 2025-02-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
    ]
